/**
 * SynTrait
 * Comparative Genomics Platform for Agronomic Trait Discovery
 *
 * Author: Balaji Muthukumar
 */
import { motion } from 'framer-motion';
import { Database, Shield, Code, Cpu } from 'lucide-react';

export function About() {
  return (
    <div className="p-10 max-w-4xl mx-auto min-h-screen flex flex-col justify-center py-20">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        <h2 className="text-sm font-mono text-cyan-400 uppercase tracking-[0.3em] mb-4">Project Information</h2>
        <h1 className="text-5xl font-extrabold text-white mb-8 tracking-tight">About SynTrait</h1>
        <div className="w-24 h-1 bg-cyan-500 mx-auto rounded-full mb-8"></div>
        <p className="text-xl text-slate-400 leading-relaxed max-w-2xl mx-auto">
          SynTrait is a computational biology platform integrating comparative genomics, orthology, synteny, and evolutionary evidence for candidate-gene prioritization.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
        <div className="glass-panel p-8 rounded-2xl border border-cyan-900/50 relative overflow-hidden group">
          <div className="absolute inset-0 bg-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
          <h3 className="text-xs font-mono text-cyan-400 uppercase tracking-widest mb-4">Creator & Developer</h3>
          <div className="text-3xl font-bold text-white mb-2">BALAJI MUTHUKUMAR</div>
          <p className="text-slate-400">
            Sole author and architect of the SynTrait platform, encompassing the bioinformatics pipeline, backend API, and interactive frontend visualizations.
          </p>
        </div>

        <div className="glass-panel p-8 rounded-2xl border border-slate-800 flex flex-col justify-center">
          <h3 className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-6">Core Technologies</h3>
          <div className="grid grid-cols-2 gap-4">
            <div className="flex items-center gap-2 text-slate-300"><Code className="w-4 h-4 text-cyan-400"/> Python / FastAPI</div>
            <div className="flex items-center gap-2 text-slate-300"><Cpu className="w-4 h-4 text-emerald-400"/> React / TypeScript</div>
            <div className="flex items-center gap-2 text-slate-300"><Database className="w-4 h-4 text-blue-400"/> SQLite / Pandas</div>
            <div className="flex items-center gap-2 text-slate-300"><Shield className="w-4 h-4 text-violet-400"/> HMMER / MCScan</div>
          </div>
        </div>
      </div>

      <div className="glass-panel p-8 rounded-2xl border border-slate-800 mb-8">
        <h3 className="text-lg font-bold text-white mb-4">Scientific Disclaimer</h3>
        <p className="text-sm text-slate-400 leading-relaxed">
          The candidate rankings generated by this platform are computational predictions based on evolutionary heuristics and public biological databases. They require experimental validation (e.g., via CRISPR knockout or transgenics) to confirm functional causality for agronomic traits.
        </p>
      </div>

      <div className="text-center mt-8">
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest">
          © Balaji Muthukumar — SynTrait
        </p>
      </div>
    </div>
  );
}
